when@dev:
    web_profiler:
        # Désactiver temporairement pour tests SEO
        toolbar: false
        # Pour réactiver : toolbar: true

    framework:
        profiler:
            collect_serializer_data: true

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
