# config/services.yaml

parameters:
    uploads_soaps_directory: "%kernel.project_dir%/public/uploads/soaps"
    uploads_users_directory: "%kernel.project_dir%/public/uploads/users"
    uploads_articles_directory: "%kernel.project_dir%/public/uploads/articles"

services:
    # Configuration par défaut pour les services
    _defaults:
        autowire: true # Injection automatique des dépendances
        autoconfigure: true # Enregistrement automatique pour commandes, subscribers, etc.
        public: false # Par défaut les services ne sont pas publics

    # Enregistre toutes les classes de src/ comme services
    App\:
        resource: "../src/"

    # Repository ResetPassword géré par Doctrine
    App\Repository\ResetPasswordRequestRepository:
        tags: ["doctrine.repository_service"]

    # ⚠️ Ne rien ajouter pour ResetPasswordCleaner : le bundle s'en occupe automatiquement
